// This file is generated by GoBuildWeb
// Containing all the assets mapping data for your router reverse lookup
// Better not to edit this.

package main

var allAssetsMapping = map[string]string{
	"images/todo_app/sprite_1x.png": "images/todo_app/fp571548d32ce8c711b398caeabb09196c-sprite_1x.png",
	"images/todo_app/500.png":       "images/todo_app/fp578bbbe3fad4aaafbe1e058c5962435f-500.png",
	"images/todo_app/sprite_2x.png": "images/todo_app/fp71cc459d2193019a629df319b361f738-sprite_2x.png",
	"javascripts/todo_app.js":       "javascripts/fp23caec76b9f6c0db6d05526ac06190f4-todo_app.js",
	"javascripts/vendor-react.js":   "javascripts/fp287e33755588fdb2037901fbe3fe718e-vendor-react.js",
	"stylesheets/todo_app.css":      "stylesheets/fp742d419dc8146ff0eb875ab74c9cc585-todo_app.css",
}
